### ISSUE TITLE
helix integration with nushell syntax highlighting

### ISSUE THREAD

**Issue by fdncred** [nushell/tree-sitter-nu#76]
we've broken the helix syntax highlighting somehow. would be nice to fix it. i've played with it and can't figure it out.

I change the rev to the latest commit in the repo and it breaks.
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/9b9ff3ad-2abd-43a9-8418-99c2a342722e)

then `hx --grammar fetch` and `hx --grammar build`
```nushell
❯ hx --grammar fetch
Fetching 169 grammars
168 up to date git grammars
1 updated grammars
        nu now on 2d0dd587dbfc3363d2af4e4141833e718647a67e
❯ hx --grammar build
Building 169 grammars
168 grammars already built
1 grammars built now
        ["nu"]
```

**Comment by fdncred** [comment]
@kit494way Looking at blame on github https://github.com/nushell/tree-sitter-nu/blame/main/queries/nu/highlights.scm, it hasn't changed in 8 months if I'm reading it right.

**Comment by kit494way** [comment]
@fdncred The `def-env` keyword and some of the file size units have been removed.
See history https://github.com/nushell/tree-sitter-nu/commits/main/queries/nu/highlights.scm

**Comment by fdncred** [comment]
@kit494way oh, you're definitely right. i guess blame only shows what's left in the file. These changes seem pretty minor though other than the one moving the location of the scm files. i was thinking it could be due to the new location of the scm files but i figured the package.json would be good enough. i'm just not real sure how to test exactly.

**Comment by kit494way** [comment]
I'm not familiar with helix, but it looks like you need to manually download highlights.scm and place it in the configuration directory.
https://github.com/nushell/tree-sitter-nu/blob/main/installation/helix.md#installing-up-to-date-grammar-from-this-repo

**Comment by fdncred** [comment]
yes, i've been using this with helix for a while now and highlighting just stopped a few commits ago. not sure which commit. i suspect the one with the files moving folders.

**Comment by fdncred** [comment]
This is the first bad commit that broke the syntax highlighting as per git bisect.

f8ae53195512aafc413b994ae7da0a6261eafa2a is the first bad commit
commit f8ae53195512aafc413b994ae7da0a6261eafa2a
Author: KITAGAWA Yasutaka <kit494way@gmail.com>
Date:   Sun Jan 21 15:31:08 2024 +0900

    Remove unsupported units

    ref. https://github.com/nushell/nushell/pull/9427

 grammar.js          |      2 -
 src/grammar.json    |     52 +-
 src/node-types.json |     88 -
 src/parser.c        | 263539 ++++++++++++++++++++++++-------------------------
 4 files changed, 131366 insertions(+), 132315 deletions(-)

**Comment by kit494way** [comment]
commit [f8ae531](https://github.com/nushell/tree-sitter-nu/commit/f8ae53195512aafc413b994ae7da0a6261eafa2a) removed nodes such as `zb` and `zib` from the grammar, but highlight.scm is left with these nodes.
When invalid nodes are used in a query, tree-sitter throws an error.
https://github.com/nushell/tree-sitter-nu/actions/runs/7599565579/job/20696740763#step:7:207

This bug has already been fixed in the next commit [06ab929](https://github.com/nushell/tree-sitter-nu/commit/06ab9291d6ae83f0c4b683909230ae51b797f66b).

I use neovim and highlighting works.
I built helix from source, fetch and built the latest tree-sitter-nu, and manualy palced the latest highlights.scm in `~/.config/helix/runtime/queries/nu` and highlighting works.

If the highlighting still does not work after updating highlights.scm, I don't know why.

**Comment by fdncred** [comment]
ok, one thing is for sure. we need to open a pr to helix to update the highlights.scm and commit for tree-sitter-nu.

Having said that, I'm still having problems and I'm not sure how to debug it.

Build Helix without issue
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/a9c29d20-b87e-4da4-955f-0f6a36c6a0c1)

Helix thinks nu is configured right.
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/f1e7c87f-db39-4612-986c-b702c74fcc7c)

No syntax highlighting
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/c6804c64-85d4-4e2b-ae17-0aa478ef21cb)

**Comment by fdncred** [comment]
Just found this `:log-open`. Not sure what to do about it yet.
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/58831285-a942-4880-8836-f5a1af13f307)

**Comment by fdncred** [comment]
Ugh, my tree-sitter-nu main was not up to date. It had a 3-day old highlights.scm which still had def-env in it. Updating and coping the *.scm files worked.

At least I know about `:log-open` now. Thanks for your help @kit494way.

One last thing, can you show me how you have tree-sitter-nu configured in nvim?

**Comment by kit494way** [comment]
I use [lazy.nvim](https://github.com/folke/lazy.nvim) to install the nvim-treesitter plugin and configure it for tree-sitter-nu as follows

```lua
{
  "nvim-treesitter/nvim-treesitter",
  build = function()
    local ts_update = require("nvim-treesitter.install").update { with_sync = true }
    ts_update()
  end,
  config = function()
    local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
    parser_config.nu = {
      install_info = {
        -- url = "https://github.com/nushell/tree-sitter-nu",
        url = "~/projects/tree-sitter-nu",
        files = { "src/parser.c" },
        branch = "main",
      },
      filetype = "nu",
    }
  end,
}
```

I manualy copy highlights.scm to ~/.config/nvim/queries/nu.
Then execute `:TSInstall nu` to install tree-sitter-nu.
